apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-test
  labels:
    app: k8-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8-test
  template:
    metadata:
      labels:
        app: k8-test
    spec:
      containers:
        - name: k8-test
          image: k8-test:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
